### ISSUE TITLE
Docs don't work for Case Insensitive File Systems (OS X, Windows)

### ISSUE THREAD

**Issue by delwaterman** [go101/golds#20]
My colleague generated docs using this project and checked it into git repo. The generated files contained many files with the same name but with different cases. For example the generator created the files:

```
docs/imp/github.com/golang/protobuf/jsonpb.AnyResolver.html
docs/imp/github.com/golang/protobuf/jsonpb.anyResolver.html
```

When I attempted to clone this repo on an OS X laptop I got the following errors:

```
warning: the following paths have collided (e.g. case-sensitive paths
on a case-insensitive filesystem) and only one from the same
colliding group is in the working tree:
```

Even setting `git config core.ignorecase` did not fix the issue. Understandably it would be better if these file systems respected case, but that's unlikely to change anytime in the future.

Is it possible to change the naming of files to account for case insensitive file systems?

**Comment by go101** [comment]
@delwaterman
Thanks for this finding.
I will find a way to resolve this problem.

**Comment by go101** [comment]
@delwaterman
This problem should be fixed on tip. If you find it still exists, fell free to reopen this issue.

**Comment by delwaterman** [comment]
Thanks we'll give it a shot

**Comment by go101** [comment]
BTW, if you use the `-only-list-exporteds` flag, the file `jsonpb.anyResolver.html` will not produced at all now.

**Comment by jcmuller** [comment]
Hi there. Thanks for adding this!

I just tried running 

```
golds -dir=docs -only-list-exporteds -gen ./...
```

and it fails with 
```
tool_gen-docs.go:609: Generated imp/vendor/golang.org/x/text/transform.Reader.html (size: 1954).
tool_gen-docs.go:609: Generated imp/vendor/golang.org/x/text/transform.Writer.html (size: 2825).
tool_gen-docs.go:609: Generated imp/vendor/golang.org/x/text/unicode/bidi.Run.html (size: 2421).
panic: should not go here (use): net.family

goroutine 7078 [running]:
go101.org/golds/internal/server.(*docServer).buildReferencesData(0xc000160000, 0xc0333f3fa5, 0x3, 0xc035acd780, 0x2, 0x2, 0xc035acd780, 0x2, 0x2)
        /usr/local/sources/golang/1.16.4/packages/pkg/mod/go101.org/golds@v0.2.9/internal/server/page_identifier-references.go:377 +0x14f7
go101.org/golds/internal/server.(*docServer).identifierReferencePage(0xc000160000, 0xabd7d0, 0xc01bd70030, 0xc025a1a400, 0xc0333f3fa5, 0x3, 0xc0333f3faa, 0x13)
        /usr/local/sources/golang/1.16.4/packages/pkg/mod/go101.org/golds@v0.2.9/internal/server/page_identifier-references.go:86 +0x411
go101.org/golds/internal/server.(*docServer).ServeHTTP(0xc000160000, 0xabd7d0, 0xc01bd70030, 0xc025a1a400)
        /usr/local/sources/golang/1.16.4/packages/pkg/mod/go101.org/golds@v0.2.9/internal/server/server.go:239 +0xcd9
go101.org/golds/internal/server.GenDocs.func1(0xc0333f3fa0, 0x1d, 0xc035ae2000, 0x1, 0x3, 0x0, 0x0)
        /usr/local/sources/golang/1.16.4/packages/pkg/mod/go101.org/golds@v0.2.9/internal/server/tool_gen-docs.go:516 +0x9c
go101.org/golds/internal/server.GenDocs.func3(0xc026946240, 0xc0038ea000)
        /usr/local/sources/golang/1.16.4/packages/pkg/mod/go101.org/golds@v0.2.9/internal/server/tool_gen-docs.go:565 +0xdd
created by go101.org/golds/internal/server.GenDocs
        /usr/local/sources/golang/1.16.4/packages/pkg/mod/go101.org/golds@v0.2.9/internal/server/tool_gen-docs.go:558 +0x43d
'golds -dir=docs -only-list-exporteds -gen ./...' time: 7.481s, cpu: 244%, mem: 1040
```

**Comment by go101** [comment]
@jcmuller 
Thanks for finding this silly bug.
It should be fixed in v0.3.0

**Comment by go101** [comment]
> BTW, if you use the -only-list-exporteds flag, the file jsonpb.anyResolver.html will not produced at all now.

I suddenly realized that this is a mistake. So this file will be produced again in v0.3.1.

**Comment by delwaterman** [comment]
This is working for us now. Thank you!
