### ISSUE TITLE
panic: writeExternalSourceCodeLink error: buildExternelSourceLink: source file github.com/PagerDuty^9f750/go-pagerduty/client.go not found

### ISSUE THREAD

**Issue by alecthomas** [go101/golds#24]
This started happening when we upgraded from go-1.16 to go-1.17:

```
panic: writeExternalSourceCodeLink error: buildExternelSourceLink: source file github.com/PagerDuty^9f750/go-pagerduty/client.go not found

goroutine 39437 [running]:
go101.org/golds/internal/server.buildPageHref({{0x1034496a3, 0x3}, {0x14007da3830, 0x2c}}, {{0x1034496ca, 0x3}, {0x1409d8a7480, 0x31}}, 0x140b4119630, {0x0, ...}, ...)
	/Users/aat/go/pkg/mod/go101.org/golds@v0.3.7-0.20211104161235-253472ce531b/internal/server/tool_gen-docs.go:357 +0xbd4
go101.org/golds/internal/server.writeSrouceCodeLineLink(0x140b4119630, 0x140890cb8c0, {{0x14008fcbce0, 0x66}, 0x793, 0x4a, 0x2}, {0x140ad4fe89a, 0x2}, {0x0, ...})
	/Users/aat/go/pkg/mod/go101.org/golds@v0.3.7-0.20211104161235-253472ce531b/internal/server/page_source-code.go:1662 +0x228
go101.org/golds/internal/server.(*docServer).writeMethodForListing(0x14000138000, 0x140b4119630, 0x140890f0840, 0x140725167e0, 0x1409c3c7650, 0x1, 0x0)
	/Users/aat/go/pkg/mod/go101.org/golds@v0.3.7-0.20211104161235-253472ce531b/internal/server/page_package-details.go:1790 +0x25c
go101.org/golds/internal/server.(*docServer).buildPackageDetailsPage.func9.4.1(0x14009593ac8, 0x1400959356f, 0x140095935b0, 0x140b4119630, 0x14000138000, 0x1400aab04b0, 0x1409c129900)
	/Users/aat/go/pkg/mod/go101.org/golds@v0.3.7-0.20211104161235-253472ce531b/internal/server/page_package-details.go:506 +0x124
go101.org/golds/internal/server.(*docServer).buildPackageDetailsPage.func9.4()
	/Users/aat/go/pkg/mod/go101.org/golds@v0.3.7-0.20211104161235-253472ce531b/internal/server/page_package-details.go:526 +0x1ec
go101.org/golds/internal/server.writeFoldingBlock(0x140b4119630, {0x1402e5e4880, 0xa}, {0x10344c999, 0x7}, {0x10344a657, 0x5}, 0x0, 0x14009593798, 0x14009593800)
	/Users/aat/go/pkg/mod/go101.org/golds@v0.3.7-0.20211104161235-253472ce531b/internal/server/page_package-details.go:2645 +0x2cc
go101.org/golds/internal/server.(*docServer).buildPackageDetailsPage.func9()
	/Users/aat/go/pkg/mod/go101.org/golds@v0.3.7-0.20211104161235-253472ce531b/internal/server/page_package-details.go:487 +0x340
go101.org/golds/internal/server.writeFoldingBlock(0x140b4119630, {0x1402e5e4880, 0xa}, {0x10344c483, 0x7}, {0x103449b29, 0x4}, 0x0, 0x14009593b38, 0x14009593bd8)
	/Users/aat/go/pkg/mod/go101.org/golds@v0.3.7-0.20211104161235-253472ce531b/internal/server/page_package-details.go:2645 +0x2cc
go101.org/golds/internal/server.(*docServer).buildPackageDetailsPage(0x14000138000, {0x1035e4ad8, 0x140af97e150}, 0x1400aab04b0)
	/Users/aat/go/pkg/mod/go101.org/golds@v0.3.7-0.20211104161235-253472ce531b/internal/server/page_package-details.go:414 +0xefc
go101.org/golds/internal/server.(*docServer).packageDetailsPage(0x14000138000, {0x1035e4ad8, 0x140af97e150}, 0x14064ea2500, {0x140c4132145, 0x2c})
	/Users/aat/go/pkg/mod/go101.org/golds@v0.3.7-0.20211104161235-253472ce531b/internal/server/page_package-details.go:60 +0x30c
go101.org/golds/internal/server.(*docServer).ServeHTTP(0x14000138000, {0x1035e4ad8, 0x140af97e150}, 0x14064ea2500)
	/Users/aat/go/pkg/mod/go101.org/golds@v0.3.7-0.20211104161235-253472ce531b/internal/server/server.go:212 +0x898
go101.org/golds/internal/server.GenDocs.func1({0x140c4132140, 0x31})
	/Users/aat/go/pkg/mod/go101.org/golds@v0.3.7-0.20211104161235-253472ce531b/internal/server/tool_gen-docs.go:522 +0x9c
go101.org/golds/internal/server.GenDocs.func3(0x14064ea6000, 0x14028bc8060)
	/Users/aat/go/pkg/mod/go101.org/golds@v0.3.7-0.20211104161235-253472ce531b/internal/server/tool_gen-docs.go:571 +0x8c
created by go101.org/golds/internal/server.GenDocs
	/Users/aat/go/pkg/mod/go101.org/golds@v0.3.7-0.20211104161235-253472ce531b/internal/server/tool_gen-docs.go:564 +0x4f0
```

**Comment by alecthomas** [comment]
Using the following command line:

```
golds -gen -dir=docs -nouses -only-list-exporteds -wdpkgs-listing=solo -footer=none -source-code-reading=external -allow-network-connection ./...
```

**Comment by go101** [comment]
@alecthomas 
This bug should be fixed in v0.3.8. Thanks for this finding.

**Comment by alecthomas** [comment]
Thanks for fixing so promptly!

**Comment by alecthomas** [comment]
Unfortunately I think this is still occurring:

```
$ golds --version
Golds v0.3.8
$ golds -gen -dir=docs -nouses -only-list-exporteds -wdpkgs-listing=solo -footer=none -source-code-reading=external -allow-network-connection ./...
info_module.go:302: (replace) guess moudle gopkg.in/gcfg.v1 repository (to use working directory module)
tool_gen-docs.go:616: Generated index.html (size: 773110).
tool_gen-docs.go:616: Generated css/light-v0.3.8.css (size: 4342).
tool_gen-docs.go:616: Generated css/light-v0.3.7.css.css (size: 4342).
tool_gen-docs.go:616: Generated css/light-v0.3.6.css.css (size: 4342).
tool_gen-docs.go:616: Generated css/light-v0.3.5.css.css (size: 4342).
tool_gen-docs.go:616: Generated css/light-v0.3.4.css.css (size: 4342).
tool_gen-docs.go:616: Generated css/light-v0.3.3.css.css (size: 4342).
tool_gen-docs.go:616: Generated jvs/golds-v0.3.8.js (size: 12812).
tool_gen-docs.go:616: Generated jvs/golds-v0.3.7.js.js (size: 12812).
tool_gen-docs.go:616: Generated jvs/golds-v0.3.6.js.js (size: 12812).
tool_gen-docs.go:616: Generated jvs/golds-v0.3.5.js.js (size: 12812).
tool_gen-docs.go:616: Generated jvs/golds-v0.3.4.js.js (size: 12812).
tool_gen-docs.go:616: Generated jvs/golds-v0.3.3.js.js (size: 12812).
tool_gen-docs.go:616: Generated statistics.html (size: 236575).
tool_gen-docs.go:616: Generated pkg/github.com/squareup/gap.html (size: 132106).
panic: writeExternalSourceCodeLink error: buildExternelSourceLink: source file github.com/PagerDuty^9f750/go-pagerduty/client.go not found

goroutine 39491 [running]:
go101.org/golds/internal/server.buildPageHref({{0x10446c583, 0x3}, {0x14007d9b3e0, 0x2c}}, {{0x10446c5aa, 0x3}, {0x140cdbb01c0, 0x31}}, 0x140cab5b4a0, {0x0, ...}, ...)
	/Users/aat/go/pkg/mod/go101.org/golds@v0.3.8/internal/server/tool_gen-docs.go:358 +0xbd4
go101.org/golds/internal/server.writeSrouceCodeLineLink(0x140cab5b4a0, 0x14080566cc0, {{0x14008ff5ce0, 0x66}, 0x793, 0x4a, 0x2}, {0x1405e26657a, 0x2}, {0x0, ...})
	/Users/aat/go/pkg/mod/go101.org/golds@v0.3.8/internal/server/page_source-code.go:1662 +0x228
go101.org/golds/internal/server.(*docServer).writeMethodForListing(0x1400015c000, 0x140cab5b4a0, 0x14067674240, 0x1409ddd48d0, 0x14093f7aa80, 0x1, 0x0)
	/Users/aat/go/pkg/mod/go101.org/golds@v0.3.8/internal/server/page_package-details.go:1790 +0x25c
go101.org/golds/internal/server.(*docServer).buildPackageDetailsPage.func9.4.1(0x140099e9ac8, 0x140099e956f, 0x140099e95b0, 0x140cab5b4a0, 0x1400015c000, 0x140805ecff0, 0x140805e7d00)
	/Users/aat/go/pkg/mod/go101.org/golds@v0.3.8/internal/server/page_package-details.go:506 +0x124
go101.org/golds/internal/server.(*docServer).buildPackageDetailsPage.func9.4()
	/Users/aat/go/pkg/mod/go101.org/golds@v0.3.8/internal/server/page_package-details.go:526 +0x1ec
go101.org/golds/internal/server.writeFoldingBlock(0x140cab5b4a0, {0x140865ff950, 0xa}, {0x10446f87f, 0x7}, {0x10446d537, 0x5}, 0x0, 0x140099e9798, 0x140099e9800)
	/Users/aat/go/pkg/mod/go101.org/golds@v0.3.8/internal/server/page_package-details.go:2645 +0x2cc
go101.org/golds/internal/server.(*docServer).buildPackageDetailsPage.func9()
	/Users/aat/go/pkg/mod/go101.org/golds@v0.3.8/internal/server/page_package-details.go:487 +0x340
go101.org/golds/internal/server.writeFoldingBlock(0x140cab5b4a0, {0x140865ff950, 0xa}, {0x10446f369, 0x7}, {0x10446ca09, 0x4}, 0x0, 0x140099e9b38, 0x140099e9bd8)
	/Users/aat/go/pkg/mod/go101.org/golds@v0.3.8/internal/server/page_package-details.go:2645 +0x2cc
go101.org/golds/internal/server.(*docServer).buildPackageDetailsPage(0x1400015c000, {0x104608430, 0x140cc106060}, 0x140805ecff0)
	/Users/aat/go/pkg/mod/go101.org/golds@v0.3.8/internal/server/page_package-details.go:414 +0xefc
go101.org/golds/internal/server.(*docServer).packageDetailsPage(0x1400015c000, {0x104608430, 0x140cc106060}, 0x140e7b44000, {0x140d5df2145, 0x2c})
	/Users/aat/go/pkg/mod/go101.org/golds@v0.3.8/internal/server/page_package-details.go:60 +0x30c
go101.org/golds/internal/server.(*docServer).ServeHTTP(0x1400015c000, {0x104608430, 0x140cc106060}, 0x140e7b44000)
	/Users/aat/go/pkg/mod/go101.org/golds@v0.3.8/internal/server/server.go:212 +0x898
go101.org/golds/internal/server.GenDocs.func1({0x140d5df2140, 0x31})
	/Users/aat/go/pkg/mod/go101.org/golds@v0.3.8/internal/server/tool_gen-docs.go:523 +0x9c
go101.org/golds/internal/server.GenDocs.func3(0x140dbbea0c0, 0x140cc722060)
	/Users/aat/go/pkg/mod/go101.org/golds@v0.3.8/internal/server/tool_gen-docs.go:572 +0x8c
created by go101.org/golds/internal/server.GenDocs
	/Users/aat/go/pkg/mod/go101.org/golds@v0.3.8/internal/server/tool_gen-docs.go:565 +0x4f0
```

**Comment by go101** [comment]
@alecthomas 
I'm sorry the last hurry-up fix.
I just pushed v0.3.9.
Could you try if it works now?

**Comment by alecthomas** [comment]
Success! Thanks again.
